# Test Routes Configuration
# PSA routes for testing

PSA_PEUGEOT_208:
  - route: "6a7075a4fdd765ee/0000004e--1f612006dd"
    description: "Peugeot e208 2021 ACC"
  - route: "d6269483d00d8b66/0000001c--03fb9e7be9"
    description: "Peugeot 2008 2020 ACC"

PSA_PEUGEOT_508:
  - route: "4cef1f7eba322b25/00000000--dee7de3f20"
    description: "Peugeot 508 2020"
